# Lab 3


Tasks:

By using the flights data find all flights:

1. Had an arrival delay of two or more hours.

2. Flew to Houston (IAH or HOU)

3. Were operated by American, Delta

4. How many values are missing in `dep_time`?

5. Sort `flight` to find fastest flight.

6. Which flights travelled the shortest?

In [3]:
import pandas as pd

flights = pd.read_csv('https://raw.githubusercontent.com/msaricaumbc/DS_data/master/nyc_flights.csv')

In [4]:
#1
flights[flights.arr_delay>=120.0]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
119,2013,1,1,811.0,630,101.0,1047.0,830,137.0,MQ,4576,N531MQ,LGA,CLT,118.0,544,6,30,2013-01-01T11:00:00Z
151,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,MQ,3944,N942MQ,JFK,BWI,41.0,184,18,35,2013-01-01T23:00:00Z
218,2013,1,1,957.0,733,144.0,1056.0,853,123.0,UA,856,N534UA,EWR,BOS,37.0,200,7,33,2013-01-01T12:00:00Z
268,2013,1,1,1114.0,900,134.0,1447.0,1222,145.0,UA,1086,N76502,LGA,IAH,248.0,1416,9,0,2013-01-01T14:00:00Z
447,2013,1,1,1505.0,1310,115.0,1638.0,1431,127.0,EV,4497,N17984,EWR,RIC,63.0,277,13,10,2013-01-01T18:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336579,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,9E,3459,N916XJ,JFK,BNA,95.0,765,15,45,2013-09-30T19:00:00Z
336668,2013,9,30,1951.0,1649,182.0,2157.0,1903,174.0,EV,4294,N13988,EWR,SAV,95.0,708,16,49,2013-09-30T20:00:00Z
336724,2013,9,30,2053.0,1815,158.0,2310.0,2054,136.0,EV,5292,N600QX,EWR,ATL,91.0,746,18,15,2013-09-30T22:00:00Z
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,3320,N906XJ,JFK,BUF,50.0,301,18,45,2013-09-30T22:00:00Z
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,2013-10-01T00:00:00Z

In [39]:
#2
flights[(flights.dest=='IAH')|(flights.dest=='HOU')]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
32,2013,1,1,623.0,627,-4.0,933.0,932,1.0,UA,496,N459UA,LGA,IAH,229.0,1416,6,27,2013-01-01T11:00:00Z
81,2013,1,1,728.0,732,-4.0,1041.0,1038,3.0,UA,473,N488UA,LGA,IAH,238.0,1416,7,32,2013-01-01T12:00:00Z
89,2013,1,1,739.0,739,0.0,1104.0,1038,26.0,UA,1479,N37408,EWR,IAH,249.0,1400,7,39,2013-01-01T12:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336524,2013,9,30,1729.0,1720,9.0,2001.0,2010,-9.0,UA,652,N455UA,EWR,IAH,173.0,1400,17,20,2013-09-30T21:00:00Z
336527,2013,9,30,1735.0,1715,20.0,2010.0,2005,5.0,WN,2067,N296WN,EWR,HOU,188.0,1411,17,15,2013-09-30T21:00:00Z
336618,2013,9,30,1859.0,1859,0.0,2134.0,2159,-25.0,UA,1128,N14731,LGA,IAH,180.0,1416,18,59,2013-09-30T22:00:00Z
336694,2013,9,30,2015.0,2015,0.0,2244.0,2307,-23.0,UA,1545,N17730,EWR,IAH,174.0,1400,20,15,2013-10-01T00:00:00Z
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,475,N477UA,EWR,IAH,175.0,1400,21,6,2013-10-01T01:00:00Z

In [41]:
#3
flights[(flights.carrier=='AA')|(flights.carrier=='DL')]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,2013-01-01T11:00:00Z
14,2013,1,1,559.0,600,-1.0,941.0,910,31.0,AA,707,N3DUAA,LGA,DFW,257.0,1389,6,0,2013-01-01T11:00:00Z
20,2013,1,1,602.0,610,-8.0,812.0,820,-8.0,DL,1919,N971DL,LGA,MSP,170.0,1020,6,10,2013-01-01T11:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336709,2013,9,30,2032.0,2045,-13.0,2147.0,2225,-38.0,AA,371,N434AA,LGA,ORD,105.0,733,20,45,2013-10-01T00:00:00Z
336715,2013,9,30,2041.0,2045,-4.0,2147.0,2208,-21.0,DL,985,N359NB,JFK,BOS,37.0,187,20,45,2013-10-01T00:00:00Z
336718,2013,9,30,2050.0,2045,5.0,20.0,53,-33.0,DL,347,N396DA,JFK,SJU,188.0,1598,20,45,2013-10-01T00:00:00Z
336744,2013,9,30,2121.0,2100,21.0,2349.0,14,-25.0,DL,2363,N193DN,JFK,LAX,296.0,2475,21,0,2013-10-01T01:00:00Z
336751,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,185,N335AA,JFK,LAX,298.0,2475,21,40,2013-10-01T01:00:00Z

In [6]:
#4
flights.dep_time.isnull().sum()
#or
flights.dep_time.isnull().value_counts()

False    328521
True       8255
Name: dep_time, dtype: int64

In [7]:
#5
for i in flights:
    flights['speed_of_flight'] = ((flights.distance)/(flights.air_time)) 
    
flights.head()

flights.sort_values(by = 'speed_of_flight')

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed_of_flight
24098,2013,1,28,1917.0,1825,52.0,2118.0,1935,103.0,US,1860,N755US,LGA,PHL,75.0,96,18,25,2013-01-28T23:00:00Z,1.280000
248839,2013,6,29,755.0,800,-5.0,1035.0,909,86.0,B6,1491,N328JB,JFK,ACK,141.0,199,8,0,2013-06-29T12:00:00Z,1.411348
305879,2013,8,28,932.0,940,-8.0,1116.0,1051,25.0,9E,3608,N8932C,JFK,PHL,61.0,94,9,40,2013-08-28T13:00:00Z,1.540984
25455,2013,1,30,1037.0,955,42.0,1221.0,1100,81.0,9E,3667,N832AY,JFK,PHL,59.0,94,9,55,2013-01-30T14:00:00Z,1.593220
80009,2013,11,27,556.0,600,-4.0,727.0,658,29.0,US,1909,N951UW,LGA,PHL,60.0,96,6,0,2013-11-27T11:00:00Z,1.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z,NaN
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z,NaN
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z,NaN
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z,NaN
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z,NaN

In [51]:
#6
flights.sort_values(by=['distance'])

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
275945,2013,7,27,NaN,106,NaN,NaN,245,NaN,US,1632,NaN,EWR,LGA,NaN,17,1,6,2013-07-27T05:00:00Z
3083,2013,1,4,1240.0,1200,40.0,1333.0,1306,27.0,EV,4193,N14972,EWR,PHL,30.0,80,12,0,2013-01-04T17:00:00Z
16328,2013,1,19,1617.0,1617,0.0,1722.0,1722,0.0,EV,4616,N12540,EWR,PHL,34.0,80,16,17,2013-01-19T21:00:00Z
112178,2013,2,1,2128.0,2129,-1.0,2216.0,2224,-8.0,EV,4619,N13969,EWR,PHL,24.0,80,21,29,2013-02-02T02:00:00Z
19983,2013,1,23,2128.0,2129,-1.0,2221.0,2224,-3.0,EV,4619,N12135,EWR,PHL,23.0,80,21,29,2013-01-24T02:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99112,2013,12,18,928.0,930,-2.0,1543.0,1535,8.0,HA,51,N395HA,JFK,HNL,641.0,4983,9,30,2013-12-18T14:00:00Z
223207,2013,6,2,956.0,1000,-4.0,1442.0,1435,7.0,HA,51,N383HA,JFK,HNL,617.0,4983,10,0,2013-06-02T14:00:00Z
151311,2013,3,17,1006.0,1000,6.0,1607.0,1530,37.0,HA,51,N380HA,JFK,HNL,686.0,4983,10,0,2013-03-17T14:00:00Z
218562,2013,5,28,953.0,1000,-7.0,1447.0,1500,-13.0,HA,51,N385HA,JFK,HNL,631.0,4983,10,0,2013-05-28T14:00:00Z
289650,2013,8,11,950.0,1000,-10.0,1438.0,1440,-2.0,HA,51,N391HA,JFK,HNL,628.0,4983,10,0,2013-08-11T14:00:00Z